// Package vectors generates docs/test-vectors.json, the cross-implementation fixtures that the TypeScript
// implementation is tested against.
package vectors

import (
	"encoding/hex"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ethereum/go-ethereum/common"
	"github.com/nbd-wtf/go-nostr"
	"github.com/nbd-wtf/go-nostr/nip19"
	"github.com/nbd-wtf/go-nostr/nip44"

	"github.com/pad01g/proxy-shopping-go/node/internal/btc"
	"github.com/pad01g/proxy-shopping-go/node/internal/delivery"
	"github.com/pad01g/proxy-shopping-go/node/internal/evm"
	"github.com/pad01g/proxy-shopping-go/node/internal/giftwrap"
	"github.com/pad01g/proxy-shopping-go/node/internal/keys"
)

// Abandon is the BIP39 test mnemonic.
const Abandon = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"

// OrderID is the order of the vectors.
const OrderID = "000102030405060708090a0b0c0d0e0f"

// LabProxyCreationCode is proxyCreationCode() of the lab SafeProxyFactory (Safe v1.4.1 sources compiled with
// solc 0.8.28, contracts/abi/SafeProxy.creationCode.hex).
const LabProxyCreationCode = "6080604052348015600e575f5ffd5b5060405161012d38038061012d833981016040819052602b9160b2565b6001600160a01b038116608f5760405162461bcd60e51b815260206004820152602260248201527f496e76616c69642073696e676c65746f6e20616464726573732070726f766964604482015261195960f21b606482015260840160405180910390fd5b5f80546001600160a01b0319166001600160a01b039290921691909117905560dd565b5f6020828403121560c1575f5ffd5b81516001600160a01b038116811460d6575f5ffd5b9392505050565b6044806100e95f395ff3fe60806040525f80546001600160a01b03169035632cf35bc960e11b01602657805f5260205ff35b365f5f375f5f365f845af490503d5f5f3e80603f573d5ffd5b503d5ff3"

// CanonicalProxyCreationCode is SafeProxyFactory(v1.4.1).proxyCreationCode() of the canonical deployment
// 0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67 on Ethereum mainnet.
const CanonicalProxyCreationCode = "608060405234801561001057600080fd5b506040516101e63803806101e68339818101604052602081101561003357600080fd5b8101908080519060200190929190505050600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff1614156100ca576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260228152602001806101c46022913960400191505060405180910390fd5b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505060ab806101196000396000f3fe608060405273ffffffffffffffffffffffffffffffffffffffff600054167fa619486e0000000000000000000000000000000000000000000000000000000060003514156050578060005260206000f35b3660008037600080366000845af43d6000803e60008114156070573d6000fd5b3d6000f3fea264697066735822122003d1488ee65e08fa41e58e888a9865554c535f2c77126a82cb4c0f917f31441364736f6c63430007060033496e76616c69642073696e676c65746f6e20616464726573732070726f7669646564"

// KeyVector lists the public keys derived from one mnemonic.
type KeyVector struct {
	Mnemonic      string `json:"mnemonic"`
	NostrPubkey   string `json:"nostr_pubkey"`
	Npub          string `json:"npub"`
	EVMAddress    string `json:"evm_address"`
	BTCAddress    string `json:"btc_address"`
	BTCEscrowXpub string `json:"btc_escrow_xpub"`
	Libp2pPeerID  string `json:"libp2p_peer_id"`
}

// File is the whole document.
type File struct {
	Comment  string               `json:"_comment"`
	Keys     map[string]KeyVector `json:"keys"`
	Order    map[string]any       `json:"order"`
	BTC      map[string]any       `json:"btc_escrow"`
	Safe     map[string]any       `json:"safe"`
	SafeTx   map[string]any       `json:"safe_tx"`
	Delivery map[string]any       `json:"delivery"`
	GiftWrap map[string]any       `json:"gift_wrap"`
}

const comment = `Test vectors of proxy-shopping v1 (docs/spec.md), generated by the Go implementation ` +
	`(node/internal/vectors; UPDATE_VECTORS=1 go test ./internal/vectors rewrites this file). ` +
	`keys: public keys per spec §1 for the BIP39 test mnemonic ("abandon") and every lab/keys/*.mnemonic; ` +
	`btc_address is the P2WPKH of m/84'/1'/0'/0/0, btc_escrow_xpub the tpub of m/7333'/2'. ` +
	`order: §1.1 idx of order_id, the user-1 and shopper-1 order keys (m/7333'/1'/idx') and the escrow-1 key derived ` +
	`from its tpub (…/idx). btc_escrow: §5.1 witness script (U=user-1, S=shopper-1, E=escrow-1 order keys) and its ` +
	`P2WSH address. safe: §6.2 with the lab EVM accounts of user-1/shopper-1/escrow-1 as owners and placeholder ` +
	`contract addresses; proxy_creation_code is that of the lab SafeProxyFactory (Safe v1.4.1 built with solc 0.8.28; ` +
	`clients must read factory.proxyCreationCode() at run time), canonical_v141 repeats the computation with the code ` +
	`of the canonical mainnet v1.4.1 factory; the CREATE2 addresses use the placeholder factory and singleton. safe_tx: §6.4 EIP-712 hashes for chain_id 31337 and verifying contract = ` +
	`safe.address, with the 65 byte signatures (v=27/28) of the listed owners; joined_signatures are sorted by owner ` +
	`address. delivery: §4.4 ciphertext = base64(nonce || XChaCha20-Poly1305(K, nonce, JSON(address), aad=order id ` +
	`bytes)) where JSON(address) is exactly address_json; key_for_shopper/key_for_escrow are NIP-44 v2 of hex(K) from ` +
	`user-1 with the given nonces. gift_wrap: §4.1 message from user-1 to shopper-1 with a fixed one-time key and fixed ` +
	`NIP-44 nonces; unwrap wrap with the shopper-1 key to obtain seal and inner. All hex is lower case except EVM ` +
	`addresses (EIP-55).`

// Generate builds the vectors; keyDir is lab/keys.
func Generate(keyDir string) (*File, error) {
	f := &File{Comment: comment, Keys: map[string]KeyVector{}}
	sets := map[string]*keys.Set{}
	add := func(name, mnemonic string) error {
		s, err := keys.FromMnemonic(mnemonic)
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		kv, err := keyVector(strings.Join(strings.Fields(mnemonic), " "), s)
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		f.Keys[name], sets[name] = kv, s
		return nil
	}
	if err := add("abandon", Abandon); err != nil {
		return nil, err
	}
	files, err := filepath.Glob(filepath.Join(keyDir, "*.mnemonic"))
	if err != nil {
		return nil, err
	}
	sort.Strings(files)
	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			return nil, err
		}
		if err := add(strings.TrimSuffix(filepath.Base(file), ".mnemonic"), string(data)); err != nil {
			return nil, err
		}
	}
	user, shopper, escrow := sets["user-1"], sets["shopper-1"], sets["escrow-1"]
	if user == nil || shopper == nil || escrow == nil {
		return nil, fmt.Errorf("lab keys user-1, shopper-1 and escrow-1 are needed in %s", keyDir)
	}

	if err := f.addOrder(user, shopper, escrow); err != nil {
		return nil, err
	}
	if err := f.addSafe(user, shopper, escrow); err != nil {
		return nil, err
	}
	if err := f.addDelivery(user, shopper, escrow); err != nil {
		return nil, err
	}
	if err := f.addGiftWrap(user, shopper); err != nil {
		return nil, err
	}
	return f, nil
}

func keyVector(mnemonic string, s *keys.Set) (KeyVector, error) {
	xpub, err := s.EscrowXpub()
	if err != nil {
		return KeyVector{}, err
	}
	id, err := s.PeerID()
	if err != nil {
		return KeyVector{}, err
	}
	npub, err := nip19.EncodePublicKey(s.NostrPubHex())
	if err != nil {
		return KeyVector{}, err
	}
	return KeyVector{
		Mnemonic: mnemonic, NostrPubkey: s.NostrPubHex(), Npub: npub, EVMAddress: s.EVMAddress().Hex(),
		BTCAddress: s.WalletAddress(), BTCEscrowXpub: xpub, Libp2pPeerID: id.String(),
	}, nil
}

func (f *File) addOrder(user, shopper, escrow *keys.Set) error {
	idx, err := keys.OrderIndex(OrderID)
	if err != nil {
		return err
	}
	u, err := user.OrderKey(OrderID)
	if err != nil {
		return err
	}
	s, err := shopper.OrderKey(OrderID)
	if err != nil {
		return err
	}
	xpub, _ := escrow.EscrowXpub()
	e, err := keys.EscrowChildPubKey(xpub, OrderID)
	if err != nil {
		return err
	}
	f.Order = map[string]any{
		"order_id":             OrderID,
		"idx":                  idx,
		"user":                 "user-1",
		"shopper":              "shopper-1",
		"escrow":               "escrow-1",
		"user_order_path":      fmt.Sprintf("m/7333'/1'/%d'", idx),
		"user_order_pubkey":    hex.EncodeToString(u.PubKey().SerializeCompressed()),
		"shopper_order_pubkey": hex.EncodeToString(s.PubKey().SerializeCompressed()),
		"escrow_order_path":    fmt.Sprintf("m/7333'/2'/%d", idx),
		"escrow_xpub":          xpub,
		"escrow_order_pubkey":  hex.EncodeToString(e.SerializeCompressed()),
	}
	esc := btc.Escrow{User: u.PubKey(), Shopper: s.PubKey(), Escrow: e, T1: 1100, T2: 1150}
	script, err := esc.Script()
	if err != nil {
		return err
	}
	addr, err := esc.Address()
	if err != nil {
		return err
	}
	f.BTC = map[string]any{
		"t1": esc.T1, "t2": esc.T2,
		"user_pubkey": f.Order["user_order_pubkey"], "shopper_pubkey": f.Order["shopper_order_pubkey"],
		"escrow_pubkey":  f.Order["escrow_order_pubkey"],
		"witness_script": hex.EncodeToString(script),
		"address":        addr,
	}
	return nil
}

func placeholder(n byte) common.Address {
	var a common.Address
	a[19] = n
	return a
}

func (f *File) addSafe(user, shopper, escrow *keys.Set) error {
	d := &evm.Deployments{ChainID: 31337, USDC: placeholder(1), Module: placeholder(2), Setup: placeholder(3)}
	d.Safe.FallbackHandler = placeholder(4)
	d.Safe.Singleton = placeholder(5)
	d.Safe.Factory = placeholder(6)
	d.Safe.MultiSendCallOnly = placeholder(7)
	o := evm.NewOrderSafe(d, user.EVMAddress(), shopper.EVMAddress(), escrow.EVMAddress(), 1790000000, 1790003600)
	init, err := o.Initializer()
	if err != nil {
		return err
	}
	salt, err := evm.SaltNonce(OrderID)
	if err != nil {
		return err
	}
	code, _ := hex.DecodeString(LabProxyCreationCode)
	safe := evm.PredictProxy(d.Safe.Factory, d.Safe.Singleton, code, init, salt)
	canonical, _ := hex.DecodeString(CanonicalProxyCreationCode)
	canonicalSafe := evm.PredictProxy(d.Safe.Factory, d.Safe.Singleton, canonical, init, salt)
	f.Safe = map[string]any{
		"order_id": OrderID,
		"owners":   []string{o.User.Hex(), o.Shopper.Hex(), o.Escrow.Hex()},
		"usdc":     d.USDC.Hex(), "module": d.Module.Hex(), "setup": d.Setup.Hex(),
		"fallback_handler": d.Safe.FallbackHandler.Hex(), "singleton": d.Safe.Singleton.Hex(),
		"factory": d.Safe.Factory.Hex(), "multisend_call_only": d.Safe.MultiSendCallOnly.Hex(),
		"t1": o.T1, "t2": o.T2,
		"salt_nonce":          salt.String(),
		"salt_nonce_hex":      "0x" + hex.EncodeToString(common.LeftPadBytes(salt.Bytes(), 32)),
		"initializer":         "0x" + hex.EncodeToString(init),
		"proxy_creation_code": "0x" + LabProxyCreationCode,
		"address":             safe.Hex(),
		"canonical_v141": map[string]string{
			"proxy_creation_code": "0x" + CanonicalProxyCreationCode,
			"address":             canonicalSafe.Hex(),
		},
	}

	release, err := evm.ReleaseTx(d.USDC, o.Shopper, big.NewInt(89_600_000), big.NewInt(0))
	if err != nil {
		return err
	}
	split, err := evm.SplitTx(d.Safe.MultiSendCallOnly, d.USDC, []evm.Transfer{
		{To: o.User, Amount: big.NewInt(40_000_000)},
		{To: o.Shopper, Amount: big.NewInt(47_808_000)},
		{To: o.Escrow, Amount: big.NewInt(1_792_000)},
	}, big.NewInt(0))
	if err != nil {
		return err
	}
	entry := func(tx evm.SafeTx, signers map[string]*keys.Set) (map[string]any, error) {
		h := tx.Hash(d.ChainID, safe)
		sigs := map[string]string{}
		byAddr := map[common.Address][]byte{}
		for name, s := range signers {
			sig, err := evm.Sign(h, s.EVM)
			if err != nil {
				return nil, err
			}
			sigs[name] = "0x" + hex.EncodeToString(sig)
			byAddr[s.EVMAddress()] = sig
		}
		return map[string]any{
			"safe_tx": tx, "hash": h.Hex(), "signatures": sigs,
			"joined_signatures": "0x" + hex.EncodeToString(evm.JoinSignatures(byAddr)),
		}, nil
	}
	rel, err := entry(release, map[string]*keys.Set{"user-1": user})
	if err != nil {
		return err
	}
	spl, err := entry(split, map[string]*keys.Set{"escrow-1": escrow, "shopper-1": shopper})
	if err != nil {
		return err
	}
	f.SafeTx = map[string]any{"chain_id": d.ChainID, "safe": safe.Hex(), "release": rel, "split": spl}
	return nil
}

func fixedBytes(n int, start byte) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = start + byte(i)
	}
	return b
}

func (f *File) addDelivery(user, shopper, escrow *keys.Set) error {
	var k [32]byte
	copy(k[:], fixedBytes(32, 0x00))
	nonce := fixedBytes(24, 0x40)
	addr := delivery.Address{Name: "山田 太郎", PostalCode: "160-0022", Address: "東京都新宿区新宿3-1-1", Phone: "03-0000-0000"}
	ct, err := delivery.Seal(k, nonce, OrderID, addr)
	if err != nil {
		return err
	}
	wrapKey := func(to *keys.Set, nonce []byte) (string, error) {
		ck, err := nip44.GenerateConversationKey(to.NostrPubHex(), user.NostrSecretHex())
		if err != nil {
			return "", err
		}
		return nip44.Encrypt(hex.EncodeToString(k[:]), ck, nip44.WithCustomNonce(nonce))
	}
	kShopper, err := wrapKey(shopper, fixedBytes(32, 0x80))
	if err != nil {
		return err
	}
	kEscrow, err := wrapKey(escrow, fixedBytes(32, 0xa0))
	if err != nil {
		return err
	}
	f.Delivery = map[string]any{
		"order_id":     OrderID,
		"k":            hex.EncodeToString(k[:]),
		"nonce":        hex.EncodeToString(nonce),
		"address":      addr,
		"address_json": `{"name":"山田 太郎","postal_code":"160-0022","address":"東京都新宿区新宿3-1-1","phone":"03-0000-0000"}`,
		"ciphertext":   ct,
		"sender":       "user-1",
		"key_for_shopper": map[string]string{
			"recipient": "shopper-1", "nip44_nonce": hex.EncodeToString(fixedBytes(32, 0x80)), "payload": kShopper},
		"key_for_escrow": map[string]string{
			"recipient": "escrow-1", "nip44_nonce": hex.EncodeToString(fixedBytes(32, 0xa0)), "payload": kEscrow},
	}
	return nil
}

func (f *File) addGiftWrap(user, shopper *keys.Set) error {
	body := map[string]string{"text": "こんにちは"}
	inner, err := giftwrap.NewInner(user.NostrSecretHex(), shopper.NostrPubHex(), OrderID, "chat", body, nostr.Timestamp(1790000000))
	if err != nil {
		return err
	}
	eph := hex.EncodeToString(fixedBytes(32, 0x01))
	opts := giftwrap.Options{EphemeralSecret: eph, SealNonce: fixedBytes(32, 0x10), WrapNonce: fixedBytes(32, 0x30)}
	wrap, err := giftwrap.Wrap(user.NostrSecretHex(), inner, opts)
	if err != nil {
		return err
	}
	// the seal is reproduced by unwrapping one layer
	seal, err := openLayer(shopper.NostrSecretHex(), wrap)
	if err != nil {
		return err
	}
	ephPub, _ := nostr.GetPublicKey(eph)
	f.GiftWrap = map[string]any{
		"sender": "user-1", "recipient": "shopper-1",
		"ephemeral_secret": eph, "ephemeral_pubkey": ephPub,
		"seal_nip44_nonce": hex.EncodeToString(opts.SealNonce), "wrap_nip44_nonce": hex.EncodeToString(opts.WrapNonce),
		"inner": inner, "seal": seal, "wrap": wrap,
	}
	return nil
}

func openLayer(secret string, wrap *nostr.Event) (*nostr.Event, error) {
	ck, err := nip44.GenerateConversationKey(wrap.PubKey, secret)
	if err != nil {
		return nil, err
	}
	plain, err := nip44.Decrypt(wrap.Content, ck)
	if err != nil {
		return nil, err
	}
	var ev nostr.Event
	if err := ev.UnmarshalJSON([]byte(plain)); err != nil {
		return nil, err
	}
	return &ev, nil
}
