package shopweb

// UI strings. Japanese shops use "ja", the US and risky shops "en".
var texts = map[string]map[string]string{
	"ja": {
		"catalog":       "商品一覧",
		"cart":          "カート",
		"addToCart":     "カートに入れる",
		"qty":           "数量",
		"price":         "価格",
		"subtotal":      "小計",
		"shippingFee":   "送料",
		"total":         "合計",
		"checkout":      "レジに進む",
		"emptyCart":     "カートは空です。",
		"clearCart":     "カートを空にする",
		"shippingTo":    "お届け先",
		"name":          "氏名",
		"postalCode":    "郵便番号",
		"address":       "住所",
		"phone":         "電話番号",
		"placeOrder":    "注文を確定して支払いへ",
		"thanks":        "ご注文ありがとうございました。",
		"orderID":       "注文番号",
		"orderStatus":   "注文状況",
		"tracking":      "配送状況",
		"backToShop":    "買い物を続ける",
		"cashOnly":      "当店は店頭でのみ現金払いを受け付けています。オンラインでのご注文はできません。",
		"posTitle":      "店頭端末（レジ）",
		"posShipping":   "店舗からの配送",
		"posCalc":       "合計を計算",
		"cashReceived":  "現金を受け取った",
		"receipt":       "領収書",
		"receiptNo":     "領収書番号",
		"paidCash":      "現金でお支払いいただきました。",
		"paymentMethod": "支払い方法",
	},
	"en": {
		"catalog":       "Products",
		"cart":          "Cart",
		"addToCart":     "Add to cart",
		"qty":           "Quantity",
		"price":         "Price",
		"subtotal":      "Subtotal",
		"shippingFee":   "Shipping",
		"total":         "Total",
		"checkout":      "Checkout",
		"emptyCart":     "Your cart is empty.",
		"clearCart":     "Empty cart",
		"shippingTo":    "Ship to",
		"name":          "Full name",
		"postalCode":    "Postal code",
		"address":       "Address",
		"phone":         "Phone",
		"placeOrder":    "Place order and pay",
		"thanks":        "Thank you for your order.",
		"orderID":       "Order number",
		"orderStatus":   "Order status",
		"tracking":      "Shipment",
		"backToShop":    "Continue shopping",
		"cashOnly":      "Cash only, in store.",
		"posTitle":      "Store terminal",
		"posShipping":   "Ship from store",
		"posCalc":       "Calculate total",
		"cashReceived":  "Cash received",
		"receipt":       "Receipt",
		"receiptNo":     "Receipt number",
		"paidCash":      "Paid in cash.",
		"paymentMethod": "Payment",
	},
}
